#!/usr/bin/env node
import readline from 'node:readline';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const DEFAULT_ENV_TEMPLATE = `# AI Team Environment Configuration
# Generated by setup wizard

# LLM Provider Configuration
LLM_PROVIDER=openai
# OPENAI_API_KEY=sk-your-openai-key
# DEEPSEEK_API_KEY=sk-your-deepseek-key
# ANTHROPIC_API_KEY=sk-ant-api-key
# XAI_API_KEY=sk-xai-key

# Model Configuration
LLM_MODEL=gpt-4o-mini
# LLM_TEMPERATURE=0.7
# LLM_MAX_TOKENS=4096

# Server Configuration
PORT=3001
NODE_ENV=development

# Optional: Observability
# LANGSMITH_TRACING=true
# LANGSMITH_API_KEY=your-langsmith-key
# LANGSMITH_PROJECT=ai-team
# LANGFUSE_PUBLIC_KEY=your-langfuse-public-key
# LANGFUSE_SECRET_KEY=your-langfuse-secret-key

# Optional: Channels
# TELEGRAM_BOT_TOKEN=your-telegram-bot-token
# FEISHU_APP_ID=your-feishu-app-id
# FEISHU_APP_SECRET=your-feishu-secret

# Optional: Storage
# STORAGE_TYPE=sqlite
# STORAGE_PATH=./data/ai-team.db
`;

const QUESTIONS = [
  {
    key: 'LLM Provider',
    question: 'Which LLM provider do you want to use?',
    options: [
      { label: 'OpenAI (Recommended)', value: 'openai' },
      { label: 'DeepSeek', value: 'deepseek' },
      { label: 'Anthropic', value: 'anthropic' },
      { label: 'xAI', value: 'xai' },
      { label: 'Ollama (Local)', value: 'ollama' },
    ],
  },
  {
    key: 'LLM Model',
    question: 'Which model do you want to use?',
    options: [
      { label: 'GPT-4o (Best quality)', value: 'gpt-4o' },
      { label: 'GPT-4o-mini (Fast, cost effective)', value: 'gpt-4o-mini' },
      { label: 'Claude 3.5 Sonnet', value: 'claude-3-5-sonnet' },
      { label: 'DeepSeek V3', value: 'deepseek-v3' },
      { label: 'Custom model', value: 'custom' },
    ],
    when: (answers) => answers['LLM Provider'] !== 'ollama',
  },
  {
    key: 'Ollama Model',
    question: 'Which Ollama model do you want to use?',
    options: [
      { label: 'llama3.2', value: 'llama3.2' },
      { label: 'qwen2.5', value: 'qwen2.5' },
      { label: 'mistral', value: 'mistral' },
      { label: 'codellama', value: 'codellama' },
    ],
    when: (answers) => answers['LLM Provider'] === 'ollama',
  },
  {
    key: 'Observability',
    question: 'Enable observability/tracing?',
    options: [
      { label: 'No tracing (Default)', value: 'none' },
      { label: 'LangSmith (Recommended)', value: 'langsmith' },
      { label: 'Langfuse', value: 'langfuse' },
      { label: 'Both LangSmith and Langfuse', value: 'both' },
    ],
  },
  {
    key: 'Channels',
    question: 'Configure messaging channels?',
    options: [
      { label: 'Skip for now (Default)', value: 'none' },
      { label: 'Telegram Bot', value: 'telegram' },
      { label: 'Feishu (Lark)', value: 'feishu' },
      { label: 'Both Telegram and Feishu', value: 'both' },
    ],
  },
  {
    key: 'Storage',
    question: 'Choose storage backend?',
    options: [
      { label: 'JSON files (Default, simple)', value: 'json' },
      { label: 'SQLite (Recommended for production)', value: 'sqlite' },
    ],
  },
  {
    key: 'Skills',
    question: 'Install sample skills?',
    options: [
      { label: 'Yes, install sample skills (Recommended)', value: 'yes' },
      { label: 'No, I will configure manually', value: 'no' },
    ],
  },
];

function createReadline() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

function ask(question) {
  return new Promise((resolve) => {
    const rl = createReadline();
    rl.question(question + '\n> ', (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function askChoice(question, options) {
  return new Promise((resolve) => {
    console.log(`\n${question}`);
    options.forEach((opt, i) => console.log(`  ${i + 1}. ${typeof opt === 'string' ? opt : opt.label}`));
    const rl = createReadline();
    rl.question(`\nEnter number (1-${options.length}): `, (num) => {
      rl.close();
      const idx = parseInt(num, 10) - 1;
      if (idx >= 0 && idx < options.length) {
        resolve(typeof options[idx] === 'string' ? options[idx] : options[idx].value);
      } else {
        resolve(typeof options[0] === 'string' ? options[0] : options[0].value);
      }
    });
  });
}

function generateEnvConfig(answers) {
  const lines = [];
  
  const llmProvider = answers['LLM Provider'] || 'openai';
  lines.push(`LLM_PROVIDER=${llmProvider}`);
  
  if (llmProvider !== 'ollama') {
    const modelMap = {
      'gpt-4o': 'gpt-4o',
      'gpt-4o-mini': 'gpt-4o-mini',
      'claude-3-5-sonnet': 'claude-3-5-sonnet-20241022',
      'deepseek-v3': 'deepseek-chat',
    };
    const model = answers['LLM Model'] || 'gpt-4o-mini';
    lines.push(`LLM_MODEL=${modelMap[model] || model}`);
  } else {
    const ollamaModel = answers['Ollama Model'] || 'llama3.2';
    lines.push(`OLLAMA_MODEL=${ollamaModel}`);
    lines.push(`OLLAMA_BASE_URL=http://localhost:11434`);
  }
  
  lines.push('');
  lines.push('# Server Configuration');
  lines.push('PORT=3001');
  lines.push('NODE_ENV=development');
  
  const observability = answers['Observability'] || 'none';
  if (observability !== 'none') {
    lines.push('');
    lines.push('# Observability Configuration');
    if (observability === 'langsmith' || observability === 'both') {
      lines.push('LANGSMITH_TRACING=true');
      lines.push('# LANGSMITH_API_KEY=your-langsmith-api-key');
      lines.push('# LANGSMITH_PROJECT=ai-team');
    }
    if (observability === 'langfuse' || observability === 'both') {
      lines.push('LANGFUSE_ENABLED=true');
      lines.push('# LANGFUSE_PUBLIC_KEY=your-langfuse-public-key');
      lines.push('# LANGFUSE_SECRET_KEY=your-langfuse-secret-key');
    }
  }
  
  const channels = answers['Channels'] || 'none';
  if (channels !== 'none') {
    lines.push('');
    lines.push('# Messaging Channels');
    if (channels === 'telegram' || channels === 'both') {
      lines.push('# TELEGRAM_BOT_TOKEN=your-telegram-bot-token');
    }
    if (channels === 'feishu' || channels === 'both') {
      lines.push('# FEISHU_APP_ID=your-feishu-app-id');
      lines.push('# FEISHU_APP_SECRET=your-feishu-secret');
    }
  }
  
  const storage = answers['Storage'] || 'json';
  if (storage === 'sqlite') {
    lines.push('');
    lines.push('# Storage Configuration');
    lines.push('STORAGE_TYPE=sqlite');
    lines.push('STORAGE_PATH=./data/ai-team.db');
  }
  
  return lines.join('\n');
}

async function installSampleSkills(skillsRoot) {
  try {
    const skillsDir = path.join(skillsRoot, 'skills');
    await fs.mkdir(skillsDir, { recursive: true });
    
    const sampleSkills = [
      {
        id: 'hello-world',
        name: 'Hello World',
        description: 'A simple skill that returns a greeting',
      },
      {
        id: 'calculator',
        name: 'Calculator',
        description: 'Perform basic mathematical calculations',
      },
    ];
    
    for (const skill of sampleSkills) {
      const skillDir = path.join(skillsDir, skill.id);
      await fs.mkdir(skillDir, { recursive: true });
      
      const manifest = {
        id: skill.id,
        name: skill.name,
        version: '1.0.0',
        type: 'skill',
        description: skill.description,
        tags: ['sample'],
        entry: `${skill.id}.mjs`,
        requiredCapabilities: [],
        maxDurationMs: 5000,
      };
      
      const skillCode = `import { createSkillResult } from '../../../packages/skills/skill-protocol.mjs';

export async function execute(request) {
  const { payload } = request;
  const name = payload?.name || 'World';
  
  return createSkillResult({
    ok: true,
    data: {
      message: \`Hello, \${name}!\`,
      timestamp: new Date().toISOString(),
    },
  });
}

export default { execute };
`;
      
      await Promise.all([
        fs.writeFile(path.join(skillDir, 'skill.manifest.json'), JSON.stringify(manifest, null, 2)),
        fs.writeFile(path.join(skillDir, `${skill.id}.mjs`), skillCode),
      ]);
    }
    
    console.log(`Installed ${sampleSkills.length} sample skills to ${skillsDir}`);
    return true;
  } catch (error) {
    console.warn(`Failed to install sample skills: ${error.message}`);
    return false;
  }
}

async function main() {
  console.log('\n=== AI Team Setup Wizard ===\n');
  console.log('This wizard will help you configure AI Team for first-time use\n');
  console.log('Press Ctrl+C at any time to exit\n');

  const answers = {};

  for (const q of QUESTIONS) {
    if (q.when && !q.when(answers)) {
      continue;
    }
    
    const answer = await askChoice(q.question, q.options);
    answers[q.key] = answer;
    console.log(`Selected: ${answer}\n`);
    
    await new Promise(r => setTimeout(r, 100));
  }

  console.log('\nGenerating configuration...\n');

  const projectRoot = process.cwd();
  const envPath = path.join(projectRoot, '.env');
  const backupPath = `${envPath}.bak`;

  if (await fs.access(envPath).then(() => true).catch(() => false)) {
    await fs.copyFile(envPath, backupPath);
    console.log(`Backed up existing .env to ${backupPath}`);
  }

  const envContent = generateEnvConfig(answers);
  await fs.writeFile(envPath, envContent + '\n', 'utf8');
  console.log(`Configuration saved to ${envPath}`);

  if (answers['Skills'] === 'yes') {
    await installSampleSkills(projectRoot);
  }

  console.log('\n========================================');
  console.log('Setup Complete!');
  console.log('========================================\n');
  
  console.log('Next steps:');
  console.log('  1. Run: make doctor       # Check your environment');
  console.log('  2. Edit .env and add your API keys');
  console.log('  3. Run: pnpm install');
  console.log('  4. Run: make docker-start  # Or: pnpm run dev\n');
  
  console.log('For more information, see:');
  console.log('  - README.md for project overview');
  console.log('  - INSTALL.md for detailed setup guide\n');
}

main().catch((error) => {
  if (error.code === 'EINTR') {
    console.log('\nSetup cancelled by user');
    process.exit(0);
  }
  console.error('Setup failed:', error);
  process.exit(1);
});
